# Configuração básica da aplicação
spring.application.name=jogos

# Configuração do banco de dados Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-1e5f772-lsilva41559-98bf.g.aivencloud.com:16801/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_pfAKCUNcJIop44H1Zoj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


logging.level.org.springframework.security=TRACE
# ou DEBUG se TRACE for muito verboso inicialmente
# logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE

# JWT Secret Key - MUDE PARA UM VALOR SEGURO E LONGO EM PRODUÇÃO!
api.security.token.secret=senha2559
