# Configuração básica da aplicação
spring.application.name=jogos

# Configuração do banco de dados Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-back-lsilva41559-98bf.l.aivencloud.com:16801/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_b3mFWIWt0AvycOxw3Lz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


logging.level.org.springframework.security=TRACE
# ou DEBUG se TRACE for muito verboso inicialmente
# logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
